# -*- coding: utf-8 -*-
"""
GAM Prompts Module

Prompt templates for various agent operations.
"""

from .chunker_prompts import (
    CHUNK_DECISION_PROMPT,
    MEMORY_GENERATION_PROMPT,
    GENERATE_DOCUMENT_SUMMARY_PROMPT,
    DEFAULT_MEMORIZE_INSTRUCTION,
    ANALYZE_CHUNK_FORMAT_PROMPT,
    ANALYZE_MEMORY_FORMAT_PROMPT,
    CHUNK_FORMAT_ANALYSIS_SCHEMA,
    MEMORY_FORMAT_ANALYSIS_SCHEMA,
)

from .chat_prompts import (
    EXPLORATION_GUIDE,
    VIDEO_EXPLORATION_GUIDE,
)

from .skill_prompts import (
    GAM_SKILL_PROMPT,
    get_skill_prompt,
)

from .gam_prompts import (
    # Batch processing
    GAM_BATCH_MEMORIZE_CHUNK_PROMPT,
    GAM_BATCH_ORGANIZE_PROMPT,
    GAM_BATCH_DEFAULT_MEMORIZE_INSTRUCTION,
    # README generation
    GAM_GENERATE_README_PROMPT,
    GAM_GENERATE_README_SCHEMA,
    MERGE_ROOT_README_PROMPT,
    MERGE_ROOT_README_SCHEMA,
    # Taxonomy
    GENERATE_TAXONOMY_FROM_TLDR_PROMPT,
    ADJUST_TAXONOMY_WITH_TLDR_PROMPT,
    ASSIGN_CHUNK_TO_TAXONOMY_PROMPT,
    GENERATE_TAXONOMY_SCHEMA,
    ADJUST_TAXONOMY_SCHEMA,
    ASSIGN_CHUNK_SCHEMA,
    # Incremental add
    SHOULD_ADD_TO_EXISTING_PROMPT,
    SHOULD_ADD_TO_EXISTING_SCHEMA,
    ADD_CHUNKS_TO_EXISTING_TAXONOMY_PROMPT,
    ADD_CHUNKS_SCHEMA,
    REORGANIZE_TAXONOMY_PROMPT,
    REORGANIZE_TAXONOMY_SCHEMA,
)

from .video_gam_prompts import (
    VIDEO_SEGMENT_PROMPT, 
    CONTEXT_GENERATION_PROMPT, 
    VIDEO_GLOBAL_PROMPT,
    VIDEO_PROBE_PROMPT)

__all__ = [
    # Chunker prompts
    "CHUNK_DECISION_PROMPT",
    "MEMORY_GENERATION_PROMPT",
    "GENERATE_DOCUMENT_SUMMARY_PROMPT",
    "DEFAULT_MEMORIZE_INSTRUCTION",
    "ANALYZE_CHUNK_FORMAT_PROMPT",
    "ANALYZE_MEMORY_FORMAT_PROMPT",
    "CHUNK_FORMAT_ANALYSIS_SCHEMA",
    "MEMORY_FORMAT_ANALYSIS_SCHEMA",
    # Chat prompts
    "EXPLORATION_GUIDE",
    "VIDEO_EXPLORATION_GUIDE",
    # GAM prompts - Batch processing
    "GAM_BATCH_MEMORIZE_CHUNK_PROMPT",
    "GAM_BATCH_ORGANIZE_PROMPT",
    "GAM_BATCH_DEFAULT_MEMORIZE_INSTRUCTION",
    # GAM prompts - README generation
    "GAM_GENERATE_README_PROMPT",
    "GAM_GENERATE_README_SCHEMA",
    "MERGE_ROOT_README_PROMPT",
    "MERGE_ROOT_README_SCHEMA",
    # GAM prompts - Taxonomy
    "GENERATE_TAXONOMY_FROM_TLDR_PROMPT",
    "ADJUST_TAXONOMY_WITH_TLDR_PROMPT",
    "ASSIGN_CHUNK_TO_TAXONOMY_PROMPT",
    "GENERATE_TAXONOMY_SCHEMA",
    "ADJUST_TAXONOMY_SCHEMA",
    "ASSIGN_CHUNK_SCHEMA",
    # GAM prompts - Incremental add
    "SHOULD_ADD_TO_EXISTING_PROMPT",
    "SHOULD_ADD_TO_EXISTING_SCHEMA",
    "ADD_CHUNKS_TO_EXISTING_TAXONOMY_PROMPT",
    "ADD_CHUNKS_SCHEMA",
    "REORGANIZE_TAXONOMY_PROMPT",
    "REORGANIZE_TAXONOMY_SCHEMA",
    # Skill prompts
    "GAM_SKILL_PROMPT",
    "get_skill_prompt",
    
    # VIDEO GAM prompts
    "VIDEO_SEGMENT_PROMPT",
    "CONTEXT_GENERATION_PROMPT",
    "VIDEO_GLOBAL_PROMPT",
    "VIDEO_PROBE_PROMPT",
]
